version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: therapy-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  therapy-app:
    build: .
    container_name: therapy-app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped

volumes:
  ollama_data: 